// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pb/envelope.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TopicMode identifies the gossip semantics for a topic.
type TopicMode int32

const (
	TopicMode_TOPIC_BROADCAST        TopicMode = 0
	TopicMode_TOPIC_STATEFUL         TopicMode = 1
	TopicMode_TOPIC_REQUEST_RESPONSE TopicMode = 2
)

// Enum value maps for TopicMode.
var (
	TopicMode_name = map[int32]string{
		0: "TOPIC_BROADCAST",
		1: "TOPIC_STATEFUL",
		2: "TOPIC_REQUEST_RESPONSE",
	}
	TopicMode_value = map[string]int32{
		"TOPIC_BROADCAST":        0,
		"TOPIC_STATEFUL":         1,
		"TOPIC_REQUEST_RESPONSE": 2,
	}
)

func (x TopicMode) Enum() *TopicMode {
	p := new(TopicMode)
	*p = x
	return p
}

func (x TopicMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TopicMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_envelope_proto_enumTypes[0].Descriptor()
}

func (TopicMode) Type() protoreflect.EnumType {
	return &file_pb_envelope_proto_enumTypes[0]
}

func (x TopicMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TopicMode.Descriptor instead.
func (TopicMode) EnumDescriptor() ([]byte, []int) {
	return file_pb_envelope_proto_rawDescGZIP(), []int{0}
}

// GossipEnvelope is the wire format for gossip exchanges.
// The records field carries opaque serialised payloads — the gossip engine
// does not know or care about record structure. Each consumer defines its
// own record proto.
type GossipEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ExchangeMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`                          // topic name
	Mode          TopicMode              `protobuf:"varint,3,opt,name=mode,proto3,enum=whisper.v1.TopicMode" json:"mode,omitempty"` // broadcast, stateful, request_response
	Records       [][]byte               `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`                      // opaque serialised payloads (consumer-defined proto)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipEnvelope) Reset() {
	*x = GossipEnvelope{}
	mi := &file_pb_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipEnvelope) ProtoMessage() {}

func (x *GossipEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pb_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipEnvelope.ProtoReflect.Descriptor instead.
func (*GossipEnvelope) Descriptor() ([]byte, []int) {
	return file_pb_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *GossipEnvelope) GetMeta() *ExchangeMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GossipEnvelope) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GossipEnvelope) GetMode() TopicMode {
	if x != nil {
		return x.Mode
	}
	return TopicMode_TOPIC_BROADCAST
}

func (x *GossipEnvelope) GetRecords() [][]byte {
	if x != nil {
		return x.Records
	}
	return nil
}

// ExchangeMeta carries per-exchange metadata piggybacked on gossip frames.
type ExchangeMeta struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CacheFingerprint   uint64                 `protobuf:"varint,1,opt,name=cache_fingerprint,json=cacheFingerprint,proto3" json:"cache_fingerprint,omitempty"`
	Region             string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	BackpressureSignal bool                   `protobuf:"varint,3,opt,name=backpressure_signal,json=backpressureSignal,proto3" json:"backpressure_signal,omitempty"`
	HlcWatermark       uint64                 `protobuf:"varint,4,opt,name=hlc_watermark,json=hlcWatermark,proto3" json:"hlc_watermark,omitempty"` // for delta sync
	PeerId             []byte                 `protobuf:"bytes,5,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Timestamp          uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// PEX entries piggybacked on gossip
	PexEntries []*PEXEntry `protobuf:"bytes,7,rep,name=pex_entries,json=pexEntries,proto3" json:"pex_entries,omitempty"`
	// Connection counts for load balancing
	ConnectionCounts map[string]int32 `protobuf:"bytes,8,rep,name=connection_counts,json=connectionCounts,proto3" json:"connection_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Connection offer for NAT traversal signaling
	Offer         *ConnectionOffer `protobuf:"bytes,9,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeMeta) Reset() {
	*x = ExchangeMeta{}
	mi := &file_pb_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeMeta) ProtoMessage() {}

func (x *ExchangeMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pb_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeMeta.ProtoReflect.Descriptor instead.
func (*ExchangeMeta) Descriptor() ([]byte, []int) {
	return file_pb_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeMeta) GetCacheFingerprint() uint64 {
	if x != nil {
		return x.CacheFingerprint
	}
	return 0
}

func (x *ExchangeMeta) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ExchangeMeta) GetBackpressureSignal() bool {
	if x != nil {
		return x.BackpressureSignal
	}
	return false
}

func (x *ExchangeMeta) GetHlcWatermark() uint64 {
	if x != nil {
		return x.HlcWatermark
	}
	return 0
}

func (x *ExchangeMeta) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *ExchangeMeta) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExchangeMeta) GetPexEntries() []*PEXEntry {
	if x != nil {
		return x.PexEntries
	}
	return nil
}

func (x *ExchangeMeta) GetConnectionCounts() map[string]int32 {
	if x != nil {
		return x.ConnectionCounts
	}
	return nil
}

func (x *ExchangeMeta) GetOffer() *ConnectionOffer {
	if x != nil {
		return x.Offer
	}
	return nil
}

// PEXEntry is a signed peer exchange advertisement.
type PEXEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addresses     []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,3,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PEXEntry) Reset() {
	*x = PEXEntry{}
	mi := &file_pb_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PEXEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PEXEntry) ProtoMessage() {}

func (x *PEXEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pb_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PEXEntry.ProtoReflect.Descriptor instead.
func (*PEXEntry) Descriptor() ([]byte, []int) {
	return file_pb_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *PEXEntry) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PEXEntry) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *PEXEntry) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *PEXEntry) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// ConnectionOffer signals desire for a direct connection.
type ConnectionOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId    string                 `protobuf:"bytes,1,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`
	ToNodeId      string                 `protobuf:"bytes,2,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`
	Addresses     []string               `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Transport     string                 `protobuf:"bytes,4,opt,name=transport,proto3" json:"transport,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,5,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionOffer) Reset() {
	*x = ConnectionOffer{}
	mi := &file_pb_envelope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionOffer) ProtoMessage() {}

func (x *ConnectionOffer) ProtoReflect() protoreflect.Message {
	mi := &file_pb_envelope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionOffer.ProtoReflect.Descriptor instead.
func (*ConnectionOffer) Descriptor() ([]byte, []int) {
	return file_pb_envelope_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionOffer) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

func (x *ConnectionOffer) GetToNodeId() string {
	if x != nil {
		return x.ToNodeId
	}
	return ""
}

func (x *ConnectionOffer) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *ConnectionOffer) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ConnectionOffer) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *ConnectionOffer) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_pb_envelope_proto protoreflect.FileDescriptor

const file_pb_envelope_proto_rawDesc = "" +
	"\n" +
	"\x11pb/envelope.proto\x12\n" +
	"whisper.v1\"\x99\x01\n" +
	"\x0eGossipEnvelope\x12,\n" +
	"\x04meta\x18\x01 \x01(\v2\x18.whisper.v1.ExchangeMetaR\x04meta\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12)\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x15.whisper.v1.TopicModeR\x04mode\x12\x18\n" +
	"\arecords\x18\x04 \x03(\fR\arecords\"\xec\x03\n" +
	"\fExchangeMeta\x12+\n" +
	"\x11cache_fingerprint\x18\x01 \x01(\x04R\x10cacheFingerprint\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12/\n" +
	"\x13backpressure_signal\x18\x03 \x01(\bR\x12backpressureSignal\x12#\n" +
	"\rhlc_watermark\x18\x04 \x01(\x04R\fhlcWatermark\x12\x17\n" +
	"\apeer_id\x18\x05 \x01(\fR\x06peerId\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\x125\n" +
	"\vpex_entries\x18\a \x03(\v2\x14.whisper.v1.PEXEntryR\n" +
	"pexEntries\x12[\n" +
	"\x11connection_counts\x18\b \x03(\v2..whisper.v1.ExchangeMeta.ConnectionCountsEntryR\x10connectionCounts\x121\n" +
	"\x05offer\x18\t \x01(\v2\x1b.whisper.v1.ConnectionOfferR\x05offer\x1aC\n" +
	"\x15ConnectionCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x86\x01\n" +
	"\bPEXEntry\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12%\n" +
	"\x0etimestamp_unix\x18\x03 \x01(\x03R\rtimestampUnix\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\xd2\x01\n" +
	"\x0fConnectionOffer\x12 \n" +
	"\ffrom_node_id\x18\x01 \x01(\tR\n" +
	"fromNodeId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x02 \x01(\tR\btoNodeId\x12\x1c\n" +
	"\taddresses\x18\x03 \x03(\tR\taddresses\x12\x1c\n" +
	"\ttransport\x18\x04 \x01(\tR\ttransport\x12%\n" +
	"\x0etimestamp_unix\x18\x05 \x01(\x03R\rtimestampUnix\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature*P\n" +
	"\tTopicMode\x12\x13\n" +
	"\x0fTOPIC_BROADCAST\x10\x00\x12\x12\n" +
	"\x0eTOPIC_STATEFUL\x10\x01\x12\x1a\n" +
	"\x16TOPIC_REQUEST_RESPONSE\x10\x02B!Z\x1fgithub.com/bbmumford/whisper/pbb\x06proto3"

var (
	file_pb_envelope_proto_rawDescOnce sync.Once
	file_pb_envelope_proto_rawDescData []byte
)

func file_pb_envelope_proto_rawDescGZIP() []byte {
	file_pb_envelope_proto_rawDescOnce.Do(func() {
		file_pb_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_envelope_proto_rawDesc), len(file_pb_envelope_proto_rawDesc)))
	})
	return file_pb_envelope_proto_rawDescData
}

var file_pb_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_envelope_proto_goTypes = []any{
	(TopicMode)(0),          // 0: whisper.v1.TopicMode
	(*GossipEnvelope)(nil),  // 1: whisper.v1.GossipEnvelope
	(*ExchangeMeta)(nil),    // 2: whisper.v1.ExchangeMeta
	(*PEXEntry)(nil),        // 3: whisper.v1.PEXEntry
	(*ConnectionOffer)(nil), // 4: whisper.v1.ConnectionOffer
	nil,                     // 5: whisper.v1.ExchangeMeta.ConnectionCountsEntry
}
var file_pb_envelope_proto_depIdxs = []int32{
	2, // 0: whisper.v1.GossipEnvelope.meta:type_name -> whisper.v1.ExchangeMeta
	0, // 1: whisper.v1.GossipEnvelope.mode:type_name -> whisper.v1.TopicMode
	3, // 2: whisper.v1.ExchangeMeta.pex_entries:type_name -> whisper.v1.PEXEntry
	5, // 3: whisper.v1.ExchangeMeta.connection_counts:type_name -> whisper.v1.ExchangeMeta.ConnectionCountsEntry
	4, // 4: whisper.v1.ExchangeMeta.offer:type_name -> whisper.v1.ConnectionOffer
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pb_envelope_proto_init() }
func file_pb_envelope_proto_init() {
	if File_pb_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_envelope_proto_rawDesc), len(file_pb_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_envelope_proto_goTypes,
		DependencyIndexes: file_pb_envelope_proto_depIdxs,
		EnumInfos:         file_pb_envelope_proto_enumTypes,
		MessageInfos:      file_pb_envelope_proto_msgTypes,
	}.Build()
	File_pb_envelope_proto = out.File
	file_pb_envelope_proto_goTypes = nil
	file_pb_envelope_proto_depIdxs = nil
}
